# Generated by Django 5.0.6 on 2024-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=50)),
                ('h2', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('bg_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
