# Generated by Django 5.0.6 on 2024-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='bg_img',
            field=models.ImageField(upload_to='static/asset'),
        ),
    ]
