# Generated by Django 5.0.6 on 2024-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_firstpage_bg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='bg_img',
            field=models.ImageField(upload_to='portfolio-django/merchex/home/static/asset'),
        ),
    ]
