# Generated by Django 5.0.6 on 2024-05-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_journeybanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeybanner',
            old_name='organization',
            new_name='orga_img',
        ),
    ]
