# Generated by Django 5.0.6 on 2024-05-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_organization_journeybanner_orga_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeybanner',
            old_name='skils',
            new_name='skills',
        ),
    ]
